version: "3.8"

services:
  app:
    build: .
    container_name: pdf_summarizer
    volumes:
      - ./data/input:/app/data/input
      - ./data/output:/app/data/output
    env_file:
      - .env
    depends_on:
      - chromadb
    networks:
      - pdf_network

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    volumes:
      - chroma_data:/chroma/data
    environment:
      - ANONYMIZED_TELEMETRY=False
    ports:
      - "8000:8000"
    networks:
      - pdf_network

volumes:
  chroma_data:

networks:
  pdf_network:
    driver: bridge
