version: "3.8"

services:
  app:
    build: .
    container_name: pdf_summarizer
    volumes:
      - ./data/input:/app/data/input
      - ./data/output:/app/data/output
    env_file:
      - .env
    networks:
      - pdf_network

networks:
  pdf_network:
    driver: bridge
